trigger:
- main

before_script:
  - rm -rf .terraform
  - terraform --version
  - cd $TF_ROOT


stages:
  - init
  - validate
  - plan
  - pre-apply

init:
  stage: init
  script:
      - terraform init
  artifacts:
    paths:
      - $TF_ROOT

validate:
  stage: validate
  script:
    - terraform validate
  artifacts:
    paths:
      - $TF_ROOT

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
      - $TF_ROOT