trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

steps:

	https://github.com/vigneshsrini1991/azure/blob/main/module/main.tf
	terraform init
    terraform plan


- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Apply'