trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

name: Self-Hosted Agent Terraform Plan

jobs:
  
    runs-on: self-hosted
    steps:
    - name: Checkout Terraform code
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 0
    - name: Install Terraform
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install terraform
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan