# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.0.3'

- script: |
    terraform init
    terraform plan -out=tfplan
  displayName: 'Initialize and Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Apply'

