trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

steps:
- name: Print working directory
  run: |
    echo "The current working directory is: $GITHUB_WORKSPACE"


- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Apply'