trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

defaults:
    run:
      working-directory: ./tf-folder-1
steps:

- script: |
    terraform init
    terraform plan -out=tfplan
  displayName: 'Initialize and Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Apply'