trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

steps:
- task: TerraformInstaller@0
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: '1.0.3'


- script: |
    terraform init
    terraform plan -out=tfplan
  displayName: 'Initialize and Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Apply'