trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

steps:

- script: |
    echo "Hello, World!"

- script: |
    terraform apply -auto-approve
  displayName: 'Apply'