trigger:
- main

pool:
  name: Default
  demands:
   - agent.name -equals DESKTOP-7HE5D1K

steps:

- script: |
    cd $(System.DefaultWorkingDirectory)/main.tf
    terraform init
    terraform plan

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Apply'